import { Users } from '~/types/users'

export const usersEx: Users[] = [
	{
		id: '1',
		email: 'andi@mail.com',
		fullname: 'andi',
		gender: 'male',
		role: 'CEO',
	},
	{
		id: '2',
		email: 'belle@mail.com',
		fullname: 'belle',
		gender: 'female',
		role: 'People Ops',
	},
	{
		id: '3',
		email: 'charlie@mail.com',
		fullname: 'charlie',
		gender: 'female',
		role: 'Manager',
	},
	{
		id: '4',
		email: 'dexter@mail.com',
		fullname: 'dexter',
		gender: 'male',
		role: 'Leader',
	},
	{
		id: '5',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'BE',
	},
	{
		id: '6',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'FE',
	},
	{
		id: '7',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'Designer',
	},
	{
		id: '8',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'Mobile',
	},
	{
		id: '9',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'QA',
	},
	{
		id: '10',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'BE',
	},
	{
		id: '11',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'FE',
	},
	{
		id: '12',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'People Ops',
	},
	{
		id: '13',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'Manager',
	},
	{
		id: '14',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'Leader',
	},
	{
		id: '15',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'BE',
	},
	{
		id: '16',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'FE',
	},
	{
		id: '17',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'Designer',
	},
	{
		id: '18',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'Mobile',
	},
	{
		id: '19',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'QA',
	},
	{
		id: '20',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'Mobile',
	},
	{
		id: '21',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'FE',
	},
	{
		id: '22',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'People Ops',
	},
	{
		id: '23',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'Manager',
	},
	{
		id: '24',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'Leader',
	},
	{
		id: '25',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'BE',
	},
	{
		id: '26',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'FE',
	},
	{
		id: '27',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'Designer',
	},
	{
		id: '28',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'Mobile',
	},
	{
		id: '29',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'QA',
	},
	{
		id: '30',
		email: 'one@mail.com',
		fullname: 'one',
		gender: 'male',
		role: 'Mobile',
	},
]
